#!/usr/bin/env bash
# setup.sh - Homelab credential generation, 1Password storage, and .env sync
# Idempotent: safe to re-run. Creates missing 1Password items, then pulls all
# values and writes .env. Requires: 1Password CLI (op), jq

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
TAG="marlboro-nas"
VAULT="Private"         # run `op vault list` to confirm your vault name

# ─── Helpers ──────────────────────────────────────────────────────────────────

log() { echo -e "\033[1;32m==>\033[0m $1" >&2; }
err() { echo -e "\033[1;31mERROR:\033[0m $1" >&2; exit 1; }

# Create a Login item with a generated password if it doesn't exist
ensure_password() {
  local title="$1"
  local username="$2"

  if op item get "$title" --vault "$VAULT" &>/dev/null; then
    log "Item '$title' already exists, skipping"
  else
    log "Creating '$title' in 1Password..."
    op item create \
      --category Login \
      --title "$title" \
      --vault "$VAULT" \
      --tags "$TAG" \
      --generate-password="letters,digits,32" \
      username="$username" > /dev/null
  fi
}

# Create a Login item with a specific secret (e.g. hex key) if it doesn't exist
ensure_secret() {
  local title="$1"
  local username="$2"
  local secret="$3"

  if op item get "$title" --vault "$VAULT" &>/dev/null; then
    log "Item '$title' already exists, skipping"
  else
    log "Creating '$title' in 1Password..."
    op item create \
      --category Login \
      --title "$title" \
      --vault "$VAULT" \
      --tags "$TAG" \
      username="$username" \
      password="$secret" > /dev/null
  fi
}

# Pull a field from 1Password; returns empty string if item/field missing
pull_field() {
  local title="$1"
  local field="$2"
  op item get "$title" --vault "$VAULT" --fields "$field" --reveal 2>/dev/null || true
}

# ─── Preflight ────────────────────────────────────────────────────────────────

command -v op &>/dev/null || err "1Password CLI (op) not found."
command -v jq &>/dev/null || err "jq not found. Run: sudo apt install jq"
op whoami &>/dev/null || err "Not signed in to 1Password. Run: eval \$(op signin)"

log "Signed in as: $(op whoami --format=json | jq -r '.email')"
log "Ensuring credentials exist in 1Password (vault: $VAULT, tag: $TAG)..."

# ─── Create Missing Items ─────────────────────────────────────────────────────

ensure_password "Marlboro NAS - Immich DB"            "immich"
ensure_password "Marlboro NAS - qBittorrent"          "admin"
ensure_password "Marlboro NAS - Nginx Proxy Manager"  "admin@example.com"
ensure_password "Marlboro NAS - Portainer"            "admin"
ensure_password "Marlboro NAS - RomM DB"              "romm-user"
ensure_password "Marlboro NAS - RomM DB Root"         "root"
ensure_secret   "Marlboro NAS - RomM Auth Secret"     "romm" "$(openssl rand -hex 32)"

# DuckDNS token must be created manually — just warn if missing
if ! op item get "Marlboro NAS - DuckDNS" --vault "$VAULT" &>/dev/null; then
  log "WARNING: 'Marlboro NAS - DuckDNS' not found in 1Password — DUCKDNS_TOKEN will be blank"
fi

# IGDB credentials must be created manually — just warn if missing
if ! op item get "Marlboro NAS - IGDB" --vault "$VAULT" &>/dev/null; then
  log "WARNING: 'Marlboro NAS - IGDB' not found in 1Password — IGDB vars will be blank"
fi

# ScreenScraper credentials must be created manually — just warn if missing
if ! op item get "Marlboro NAS - Screenscraper" --vault "$VAULT" &>/dev/null; then
  log "WARNING: 'Marlboro NAS - Screenscraper' not found in 1Password — SCREENSCRAPER vars will be blank"
fi

# ─── Pull Credentials & Write .env ────────────────────────────────────────────

log "Pulling credentials from 1Password and writing $ENV_FILE..."

cat > "$ENV_FILE" <<EOF
# Generated by setup_script.sh — do not commit this file to git
# Credentials are stored in 1Password under tag: $TAG

IMMICH_DB_PASSWORD=$(pull_field "Marlboro NAS - Immich DB" password)
QBIT_PASSWORD=$(pull_field "Marlboro NAS - qBittorrent" password)
ROMM_ROOT_PASSWORD=$(pull_field "Marlboro NAS - RomM DB Root" password)
ROMM_DB_PASSWORD=$(pull_field "Marlboro NAS - RomM DB" password)
ROMM_SECRET_KEY=$(pull_field "Marlboro NAS - RomM Auth Secret" password)
DUCKDNS_TOKEN=$(pull_field "Marlboro NAS - DuckDNS" token)
IGDB_CLIENT_ID=$(pull_field "Marlboro NAS - IGDB" client_id)
IGDB_CLIENT_SECRET=$(pull_field "Marlboro NAS - IGDB" secret)
SCREENSCRAPER_USER=$(pull_field "Marlboro NAS - Screenscraper" username)
SCREENSCRAPER_PASSWORD=$(pull_field "Marlboro NAS - Screenscraper" password)
EOF

chmod 600 "$ENV_FILE"

log ".env written with $(grep -c '=' "$ENV_FILE") variables"

# ─── Ensure Media Directories & Ownership ────────────────────────────────────

MEDIA_DIRS=(/mnt/tank/media/movies /mnt/tank/media/tv /mnt/tank/downloads/complete /mnt/tank/downloads/incomplete)

if [ -d /mnt/tank ]; then
  for dir in "${MEDIA_DIRS[@]}"; do
    [ -d "$dir" ] || mkdir -p "$dir"
  done

  needs_fix=false
  for dir in "${MEDIA_DIRS[@]}"; do
    owner=$(stat -c '%u:%g' "$dir")
    if [ "$owner" != "1000:1000" ]; then
      needs_fix=true
      break
    fi
  done

  if $needs_fix; then
    log "Fixing media directory ownership (1000:1000)..."
    docker run --rm -v /mnt/tank:/mnt/tank alpine chown 1000:1000 "${MEDIA_DIRS[@]}"
  else
    log "Media directory ownership OK"
  fi
else
  log "WARNING: /mnt/tank not mounted — skipping media directory setup"
fi

# ─── Store Network Details ─────────────────────────────────────────────────────

if command -v tailscale &>/dev/null; then
  if ! op item get "Marlboro NAS - Network" --vault "$VAULT" &>/dev/null; then
    log "Storing network details in 1Password..."
    op item create \
      --category "Secure Note" \
      --title "Marlboro NAS - Network" \
      --vault "$VAULT" \
      --tags "$TAG" \
      "static-ip[text]=$(ip -4 addr show enp4s0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)" \
      "tailscale-hostname[text]=$(tailscale status --json | jq -r '.Self.DNSName | rtrimstr(".")')" \
      "tailscale-ip[text]=$(tailscale ip -4)" > /dev/null
  else
    log "Item 'Marlboro NAS - Network' already exists, skipping"
  fi
fi

# ─── Summary ──────────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup complete. .env written to: $ENV_FILE"
echo "  Tag: $TAG | Vault: $VAULT"
echo ""
echo "  Ready to run: docker compose up -d"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
