
base-url: "http://192.168.0.10:8194"

listen-http: ":80"

cache-file: "/var/cache/ntfy/cache.db"
cache-duration: "12h"
attachment-cache-dir: "/var/cache/ntfy/attachments"

auth-file: "/var/cache/ntfy/auth.db"
auth-default-access: "read-write"
